### ISSUE TITLE
Either resolve or suppress all the warnings when flask app is started

### ISSUE THREAD

**Issue by pulkitvyas08** [ChiragSaxena5437/PARiKSHA#24]
There are some deprecation warnings displaying when starting the run.py file. Like this:

FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning

Let's keep the console clean at start

**Comment by vu29** [comment]
@pulkitvyas08 I looked into it. It is because of the home-page..Assign it to the front-end team
@AnushkaGarg26 @ChiragSaxena5437  please look into it
**Priority : Low**
