### ISSUE TITLE
Navbar not showing in small to medium screens

### ISSUE THREAD

**Issue by pulkitvyas08** [ChiragSaxena5437/PARiKSHA#25]
Problem potentially related to #17

**Comment by pulkitvyas08** [comment]
![localhost_8080_home(Moto G4)](https://user-images.githubusercontent.com/54947769/95457673-d8120e00-098e-11eb-9cda-7453de06d7ac.png)

This is what I'm getting in small devices

**Comment by vu29** [comment]
Done!
