### ISSUE TITLE
Code to disable submit button in quizzes till all radio buttons are not selected

### ISSUE THREAD

**Issue by pulkitvyas08** [ChiragSaxena5437/PARiKSHA#39]

**Comment by vu29** [comment]
https://github.com/ChiragSaxena5437/PARiKSHA/blob/84fd026e0e36104225fcf310279ed53c98b39e1f/pariksha/student/templates/quiz.html#L47
@pulkitvyas08 The question_count variable will give the count of questions you can use it to implement the given condition.

**Comment by pulkitvyas08** [comment]
Added the feature in c7c5bfc54a284bb38020534223cb197e9dba56b7
