### ISSUE TITLE
Add code to clone a div 

### ISSUE THREAD

**Issue by pulkitvyas08** [ChiragSaxena5437/PARiKSHA#43]
To add questions to the quiz when a button is pressed, the contents of an entire div should be cloned just below the original one

**Comment by vu29** [comment]
@ChiragSaxena5437 has complete the div to be cloned @pulkitvyas08 get in touch with him and add the clone function to the html file ASAP

**Comment by pulkitvyas08** [comment]
Great work @ChiragSaxena5437! Will reopen this once the base site is complete
