### ISSUE TITLE
Fix the cards on Teacher's page

### ISSUE THREAD

**Issue by pulkitvyas08** [ChiragSaxena5437/PARiKSHA#7]
1. Increase vertical spacing between the cards
2. Have 4 cards instead of 2
3. Clicking the card picture should open the page

**Comment by ChiragSaxena5437** [comment]
Points 1 & 2 have been resolved. 3rd would be done one we go in making final routes.

**Comment by pulkitvyas08** [comment]
Now the /teachers route is not working. Please resolve this

**Comment by ChiragSaxena5437** [comment]
Fixed in commit 4047956
Thank You.
