### ISSUE TITLE
Home page not opening / Has some bug

### ISSUE THREAD

**Issue by pulkitvyas08** [ChiragSaxena5437/PARiKSHA#8]
Opening the homepage gives me this - 
![image](https://user-images.githubusercontent.com/54947769/94235846-d590cc80-ff29-11ea-844c-74dfaad0e16a.png)

Maybe I'm doing something wrong. Please reply to this issue if it's okay on someone else's end

**Comment by ChiragSaxena5437** [comment]
Please use '/home'. The Feature has been added.

**Comment by pulkitvyas08** [comment]
Issue not fixed. Please create a patch ASAP

**Comment by ChiragSaxena5437** [comment]
Fixed in  commit 4047956. Again use '/home'

**Comment by pulkitvyas08** [comment]
Problems with routes still have to be resolved. Just reference this issue and close it when that is done

**Comment by ChiragSaxena5437** [comment]
Closing on @vu29 's behalf  it was resolved before but you can see commit 8704771.
