### ISSUE TITLE
WebRTC integration 

### ISSUE THREAD

**Issue by vu29** [ChiragSaxena5437/PARiKSHA#93]
- Activate Quiz:
https://github.com/ChiragSaxena5437/PARiKSHA/blob/d6a10fb0f46649a3a8a3ad3b248fd055bf63711d/pariksha/teacher/routes.py#L72 This route is used for activating quiz and the corresponding function is https://github.com/ChiragSaxena5437/PARiKSHA/blob/d6a10fb0f46649a3a8a3ad3b248fd055bf63711d/pariksha/teacher/routes.py#L74 and the html file that lists the quizzes is 
**pariksha/teacher/templates/quiz_list_activate.html**

- Attempt Quiz:
https://github.com/ChiragSaxena5437/PARiKSHA/blob/d6a10fb0f46649a3a8a3ad3b248fd055bf63711d/pariksha/student/routes.py#L24 is the route for attempting quiz and the corresponding function is 
https://github.com/ChiragSaxena5437/PARiKSHA/blob/d6a10fb0f46649a3a8a3ad3b248fd055bf63711d/pariksha/student/routes.py#L26 and the html file that renders the quiz is **pariksha/student/templates/quiz.html**

- Submit Quiz:
https://github.com/ChiragSaxena5437/PARiKSHA/blob/d6a10fb0f46649a3a8a3ad3b248fd055bf63711d/pariksha/student/routes.py#L58 is the route for submitting the quiz (POST only) and the corresponding function is https://github.com/ChiragSaxena5437/PARiKSHA/blob/d6a10fb0f46649a3a8a3ad3b248fd055bf63711d/pariksha/student/routes.py#L60 and no separate html file for obvious reasons.

**Comment by pulkitvyas08** [comment]
The integration process would change a lot once the new system is up and running so closing for now
